### ISSUE TITLE
Ticket validation 

### ISSUE THREAD

**Issue by devjoseluis** [GTSSUG/SQLConnect#1]
Hello, I have my ticket from Eventbrite but I don't know if it is valid for the event. I have attached the screenshot of the PDF file that I received.

📸 🤔

![📸](https://user-images.githubusercontent.com/8582458/69896920-2df73d80-130a-11ea-89d8-3ee5e4c5f89b.png)

**Comment by croblesm** [comment]
The email notification with the QR code is the actual confirmation that your ticket was processed and valid.

**Comment by devjoseluis** [comment]
Thanks! See you all there! 💯
